version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 20 # Roughly half the number of dependencies
    groups:
      composer:
        update-types:
          - "patch"
    schedule:
      interval: "daily"
